// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

// jest.setTimeout(3000000);
describe('1-2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('1-2', async function() {
    await driver.get("https://stage.mobipaid.com/en/register")
    await driver.manage().window().setRect({ width: 800, height: 816 })
    await driver.findElement(By.id("signatory_first_name")).click()
    await driver.findElement(By.id("signatory_first_name")).sendKeys("Nur")
    await driver.findElement(By.id("signatory_last_name")).click()
    await driver.findElement(By.id("signatory_last_name")).sendKeys("Laili")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("has@gmail.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("La8?")
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("Personalia")
    await driver.findElement(By.css(".btn-log")).click()
    await driver.findElement(By.css(".btn-log")).sendKeys("8647511873")
    await driver.findElement(By.id("country")).click()
    {
      const dropdown = await driver.findElement(By.id("country"))
      await dropdown.findElement(By.xpath("//option[. = 'regexp:\\s+Indonesia']")).click()
    }
    await driver.findElement(By.name("state")).click()
    await driver.findElement(By.name("state")).sendKeys("Yogyakarta")
    await driver.findElement(By.css(".psa-checkbox")).click()
    await driver.findElement(By.id("btn-register")).click()
    assert(await driver.findElement(By.id("error-mob")).getText() == "Email already registered.")
    await driver.close()
  })
})
