// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

// jest.setTimeout(3000000);
describe('1-3', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('1-3', async function() {
    await driver.get("https://stage.mobipaid.com/en/register")
    await driver.manage().window().setRect({ width: 800, height: 816 })
    await driver.findElement(By.id("signatory_first_name")).sendKeys("a")
    await driver.findElement(By.id("signatory_last_name")).click()
    await driver.findElement(By.id("signatory_last_name")).sendKeys("a")
    await driver.findElement(By.css(".psa-checkbox")).click()
    await driver.findElement(By.id("btn-register")).click()
    await driver.close()
  })
})
